# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 01:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name=b'T\xc3\xadtulo')),
                ('description', models.TextField(max_length=800, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name=b'Pre\xc3\xa7o')),
                ('image', models.ImageField(default=b'images/None/no-img.jpg', upload_to=b'images/', verbose_name=b'Foto')),
                ('status', models.IntegerField(choices=[(1, b'Dispon\xc3\xadvel'), (2, b'Indispon\xc3\xadvel')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Pendente'), (2, b'Cancelado'), (3, b'Confirmado')], default=1)),
                ('request_date', models.DateTimeField()),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name=b'Meses')),
                ('payment', models.IntegerField(choices=[(1, b'Dinheiro'), (2, b'Troca')], verbose_name=b'Forma de pagamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alugueme.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
