# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 21:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('alugueme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=800, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Troca')], verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Cancelado'), (3, 'Confirmado')], default=1),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alugueme.User'),
        ),
    ]
