# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueme', '0002_auto_20170715_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c_max_items',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='c_max_rents',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=10))]),
        ),
        migrations.AddField(
            model_name='profile',
            name='rents',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=3))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, b'Dispon\xc3\xadvel'), (2, b'Indispon\xc3\xadvel'), (3, b'Inativo')], default=1),
        ),
    ]
