# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 21:55
from __future__ import unicode_literals

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueme', '0004_auto_20170715_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='stars',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
    ]
