# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 02:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueme', '0005_auto_20170715_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='c_max_items',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='c_max_rents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='items',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rents',
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_items',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_rents',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
